apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-two
  labels:
    app: nginx-two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
