apiVersion: v1
kind: Pod
metadata:
  name: hook-vault-config
  annotations:
    "helm.sh/hook": "post-install"
spec:
  containers:
  - name: vault-config-hook
    image: curlimages/curl
    env:
      - name: KHOST
        value: example.com
#      - name: ADMIN_TK
#        valueFrom:
#          secretKeyRef:
#            name: vault-token
#            key: token
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c"]
    args:
      - >
        TK=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
        CA=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt);
        echo "{ \"kubernetes_host\": \"$KHOST\",\"kubernetes_ca_cert\":   \"$CA\" }" > /tmp/payload.json;
        more /tmp/payload.json;
#     curl --header "X-Vault-Token: $ADMIN_TK"  --request POST  --data @/tmp/payload.json http://external-vault:8200
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
