# Default values for kube-prometheus-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name in place of kube-prometheus-stack for `app:` labels
##
nameOverride: "kube-prom-stack" #

## Override the deployment namespace
##
namespaceOverride: "monitoring" #

## Provide a k8s version to auto dashboard import script example: kubeTargetVersionOverride: 1.16.6
##
kubeTargetVersionOverride: "1.24.8" #

## Allow kubeVersion to be overridden while creating the ingress
##
kubeVersionOverride: "1.24.8" #

## Provide a name to substitute for the full names of resources
##
fullnameOverride: "monitoring" #

## Labels to apply to all resources
##
commonLabels: {} #
# scmhash: abc123
# myLabel: aakkmd

## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  podDisruptionBudget:  #
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

  ## Alertmanager configuration directives
  ## ref: https://prometheus.io/docs/alerting/configuration/#configuration-file
  ##      https://prometheus.io/webtools/alerting/routing-tree-editor/
  ##
  config:
    global:
      resolve_timeout: 5m #
    inhibit_rules: #
      - source_matchers:
          - 'severity = critical'
        target_matchers:
          - 'severity =~ warning|info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'severity = warning'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
          - 'alertname'
      - source_matchers:
          - 'alertname = InfoInhibitor'
        target_matchers:
          - 'severity = info'
        equal:
          - 'namespace'
 # https://fabianlee.org/2022/07/03/prometheus-external-template-for-alertmanager-html-email-with-kube-prometheus-stack/
    route:
      group_by: ['namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
    #  receiver: email_platform #
      routes:
      - receiver: 'null'
        matchers:
          - alertname =~ "InfoInhibitor|Watchdog"
      #- receiver: email_platform #
      #  matchers:
      #    - alertname =~ "InfoInhibitor|Watchdog"
      #- receiver: email_platform #
      #  continue: true
    receivers: #
    - name: 'null'
    #- name: email_platform
    #  # override subject line and html content
    #  email_configs:
    #  - to: platform@amprion
    #    send_resolved: true
    #    headers:
    #      subject: "{{ .Status | toUpper }} {{ .CommonLabels.env }}:{{ .CommonLabels.cluster }} {{ .CommonLabels.alertname }}"
    #    # refers to named template evaluated by AlertManager at runtime
    #    html: '{{ template "emaildefaulthtml" . }}'
    #    text: '{{ template "emaildefaulttext" . }}'

  ## Settings affecting alertmanagerSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#alertmanagerspec
  ##
  alertmanagerSpec:
    ## Image of Alertmanager
    ##

    ## Size is the expected size of the alertmanager cluster. The controller will eventually make the size of the
    ## running cluster equal to the expected size.
    replicas: 1 #

    ## Time duration Alertmanager shall retain data for. Default is '120h', and must match the regular expression
    ## [0-9]+(ms|s|m|h) (milliseconds seconds minutes hours).
    ##
    retention: 120h #

    ## Define resources requests and limits for single Pods.
    ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources: #
      requests:
        memory: 400Mi

## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  # Enabling/Disabling Grafana on App-Sites
  enabled: false

  # Get Admin-Login for Grafana from global User
  admin:
    existingSecret: ""
    userKey: admin-user
    passwordKey: admin-password

  # adminPassword: prom-operator #

  ingress: #
    enabled: true

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts:
      - grafana-default-not-set.example.com

    ## Path for grafana ingress
    path: /

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: []
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com


## Component scraping kube proxy
##
kubeProxy:
  enabled: true

  service:
    enabled: true
    port: 10249
    targetPort: 10249

    # Custom Selector for RKE2
    selector:
      component: kube-proxy


## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  ## Resource limits & requests
  ##
  resources: #
    limits:
      cpu: 400m
      memory: 200Mi
    requests:
      cpu: 200m
      memory: 100Mi

  ## Prometheus-operator image
  ##

  ## Prometheus image to use for prometheuses managed by the operator
  ##
  # prometheusDefaultBaseImage: prometheus/prometheus

  ## Prometheus image registry to use for prometheuses managed by the operator
  ##
  # prometheusDefaultBaseImageRegistry: quay.io

  ## Alertmanager image to use for alertmanagers managed by the operator
  ##
  # alertmanagerDefaultBaseImage: prometheus/alertmanager

  ## Alertmanager image registry to use for alertmanagers managed by the operator
  ##
  # alertmanagerDefaultBaseImageRegistry: quay.io

  ## Prometheus-config-reloader
  ##
  prometheusConfigReloader:

    # resource config for prometheusConfigReloader
    resources: #
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi

  ## Thanos side-car image when configured
  ##

## Deploy a Prometheus instance
##
prometheus:

  ## Configure pod disruption budgets for Prometheus
  ## ref: https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget
  ## This configuration is immutable once created and will require the PDB to be deleted to be changed
  ## https://github.com/kubernetes/kubernetes/issues/45398
  ##
  podDisruptionBudget: #
    enabled: false
    minAvailable: 1
    maxUnavailable: ""

  ingress: #
    enabled: true

    ## Hostnames.
    ## Must be provided if Ingress is enabled.
    ##
    # hosts:
    #   - prometheus.domain.com
    #hosts: []
    hosts:
      - prometheus-default-not-set.example.com

    ## Paths to use for ingress rules - one path should match the prometheusSpec.routePrefix
    ##
    paths: []
    # - /

    ## For Kubernetes >= 1.18 you should specify the pathType (determines how Ingress paths should be matched)
    ## See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#better-path-matching-with-path-types
    # pathType: ImplementationSpecific

    ## TLS configuration for Prometheus Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: []
      # - secretName: prometheus-general-tls
      #   hosts:
      #     - prometheus.example.com

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:
    ## Image of Prometheus.
    ##

    # Set Custom Liveness Probe settings for federated prometheus
    containers:
      - name: prometheus
        livenessProbe:
          failureThreshold: 6
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 30
    ## How long to retain metrics
    ##
    # Retention Time can be short, because federated prometheus scrapes the data for long-term usage
    retention: 1d #

    ## Maximum size of metrics
    ##
    retentionSize: "" #

    ## Number of replicas of each shard to deploy for a Prometheus deployment.
    ## Number of replicas multiplied by shards is the total number of Pods created.
    ##
    replicas: 1 #

    ## Resource limits & requests
    ##
    resources: #
      requests:
        memory: 800Mi
      limits:
        memory: 1600Mi
