apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  {{- if .Values.namespace.labels }}
  labels:
    {{- range $key, $value := .Values.namespace.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  {{- if .Values.namespace.annotations }}
  annotations:
    {{- range $key, $value := .Values.namespace.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
