kind: ClusterGroup
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: ten
  namespace: fleet-default
spec:
  # This is the standard metav1.LabelSelector format to match clusters by labels
  selector:
    matchLabels:
      cluster: '10'
